version: "3"

services:
  namenode:
    image: nicholas/hadoop-namenode:master
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      TZ: "Asia/Seoul"
      CLUSTER_NAME: "test"
#      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode:
    image: nicholas/hadoop-datanode:master
    container_name: datanode
    restart: always
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      TZ: "Asia/Seoul"
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
  
  resourcemanager:
    image: nicholas/hadoop-resourcemanager:master
    container_name: resourcemanager
    restart: always
    ports:
      - 8088:8088
    environment:
      TZ: "Asia/Seoul"
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - ./hadoop.env
    depends_on:
      - "namenode"

  nodemanager1:
    image: nicholas/hadoop-nodemanager:master
    container_name: nodemanager
    restart: always
    environment:
      TZ: "Asia/Seoul"
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    depends_on:
      - "namenode"
  
  historyserver:
    image: nicholas/hadoop-historyserver:master
    container_name: historyserver
    restart: always
    ports:
      - 8188:8188
    environment:
      TZ: "Asia/Seoul"
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    depends_on:
      - "namenode"

  hiveserver:
    image: nicholas/hadoop-eco-hive:master
    container_name: hiveserver
    restart: always
    ports:
      - 10000:10000
    environment:
      TZ: "Asia/Seoul"
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    depends_on:
      - "metastore-db"

  metastore-db:
    image: mariadb
    container_name: metastore-db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQLD_OPTS: "--skip-grant-tables"
    volumes:
      - hive_metastoredb:/var/lib/mysql 
    depends_on:
      - "resourcemanager"
  
volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
  hive_metastoredb:
