FROM nginx

MAINTAINER "Nicholas H. Park <mailto:nicholas.hpark@gmail.com>"

COPY default.conf /etc/nginx/conf.d/default.conf
COPY materialize.min.css /data/css/materialize.min.css
COPY hadoop.css /data/css/hadoop.css
